In [60]:
import pandas as pd
import numpy as np
from sklearn.manifold import TSNE
from bokeh.io import show, output_notebook, push_notebook
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
output_notebook()
import random

Loading BokehJS ...

In [61]:
matrix = np.matrix([
    [1, 1, 1, 1, 0, 1], 
    [1, 1, 1, 1, 0, 1], 
    [1, 1, 1, 1, 0, 1], 
    [1, 1, 1, 1, 0, 1], 
    [1, 1, 1, 1, 0, 1], 
    [1, 1, 1, 1, 0, 1],
    [0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0]])

In [103]:
matrix = np.array([[random.choice([0,1]) for _ in range(10)] for _ in range(10)])

matrix = np.append(matrix, [np.ones(10)], axis=0)
matrix[5,5] = float('nan')
print(matrix)

[[ 1.  1.  1.  1.  0.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  0.  0.  1.  0.  1.]
 [ 1.  1.  1.  0.  1.  1.  1.  0.  1.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  0. nan  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  1.  0.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  0.  1.  1.  1.  0.]
 [ 0.  1.  1.  0.  1.  1.  0.  0.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [104]:
model = TSNE(n_components=2, perplexity=30)
tsne_features = model.fit_transform(matrix)
df = pd.DataFrame()
df['X'] = tsne_features[:, 0]
df['Y'] = tsne_features[:, 1]

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [100]:
print(tsne_features)

[[ 4.985598    3.477528  ]
 [ 3.0767384   1.3601538 ]
 [ 9.305388   -1.41668   ]
 [-3.481945   -1.5299535 ]
 [ 7.183463    6.725907  ]
 [ 2.4519365   4.7450423 ]
 [ 6.0818124   2.9374483 ]
 [ 1.5315775  -1.4857349 ]
 [ 2.9514482   0.42162567]
 [ 9.252495   -1.2004204 ]
 [ 0.9897591  -1.6669424 ]
 [ 5.400348   -1.9084598 ]
 [-7.369544    2.335038  ]
 [-2.5944538   5.1701756 ]
 [-3.3610299   5.092953  ]
 [-7.562676   -3.5768754 ]
 [ 3.4491334   6.916187  ]
 [ 0.82817453  9.836351  ]
 [-2.0934398  -1.0966786 ]
 [ 3.908072    0.08908863]
 [-2.0985162   2.7046638 ]
 [ 6.296803    9.141333  ]
 [-3.2210474  -6.212532  ]
 [ 4.7525663  -4.5634055 ]
 [-1.6649727  -5.4039063 ]
 [-9.23726    -4.9379625 ]
 [ 0.64665556 -5.0184636 ]
 [ 0.6142585   0.3460065 ]
 [ 6.9234486   3.758348  ]
 [-3.2427974   8.994672  ]
 [ 2.5886068  -3.62746   ]
 [ 3.9714522   5.5641546 ]
 [ 2.5654647  -0.9602686 ]
 [-3.0071208   0.18144234]
 [ 3.15295    -6.1156397 ]
 [-0.83562624 -1.7551078 ]
 [ 4.1635776  -0.96471816]
 

In [101]:
source = ColumnDataSource(df)

plot = figure(x_axis_label = 'T-SNE 1', 
              y_axis_label = 'T-SNE 2')

plot.circle(
    x = 'X', 
    y = 'Y',
    source = source, 
    size = 10, color = '#FF7373', alpha = .8
)

show(plot)